import type { NextPage } from "next"
import Head from "next/head"
import { Examples } from "../components/Examples"
import { ImgGallery } from "../components/ImgGallery"
import { Button } from "../components/PrimaryButton"
import { SocialIcon } from "../components/SocialIcon"

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>blocktunes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preload" href={"/images/neon_box_splash.jpeg"} as="image" />
      </Head>

      <div>
        <header>
          <div className="logo-container">
            <p>blocktunes</p>
          </div>
          <div className="contact-container">
            <SocialIcon
              link={"https://www.instagram.com/blocktunesnft/?hl=en"}
              src={"/images/instagram.svg"}
            />
            <SocialIcon
              link={"https://twitter.com/blocktunesnft"}
              src={"/images/twitter.svg"}
            />
            <Button label="Connect Wallet" />
          </div>
        </header>
        <main>
          <section className="splash">
            <div className="overlay">
              <h1>the soundtrack for web3</h1>
              <Button label="Mint Track" />
              <p id="whitelist-flash">the mintlist has begun</p>
            </div>
          </section>
          <Examples />

          <section className="overview one">
            <div className="overlay">
              <p className="primary">the most extensive music NFT to date ⚡</p>

              <p className="secondary">
                ...and a new model for quality music that can reward everyone
                involved
              </p>

              <p className="primary">
                blocktunes will be formed of musical “building blocks” -
                instrumentals, vocals, drums etc, that can be pulled together by
                bespoke music logic to create a limited collection of unique
                tracks
              </p>
            </div>
          </section>
          <section className="overview two">
            <div className="overlay">
              <p className="primary">
                over thirty top musicians are busy in the studio recording and
                composing vocals and instrumentals: the musical "traits" from
                which buyers can mint their very own unique blocktune 🎧
              </p>

              <p className="secondary">
                this will be the most extensive music NFT to date... so let’s
                set a precedent and write some history 😎
              </p>
            </div>
          </section>
          <section className="contributors-gallery">
            <div className="overlay"></div>
            <ImgGallery />
          </section>
        </main>
        <footer>
          <p>blocktunes</p>
        </footer>
      </div>
    </div>
  )
}

export default Home
